Update config.yml
cmusv-sem/S23SB-SEM-IR pull request #98
Opened 2023-03-23 20:21 UTC by XiangjieChen1

# Description

Please include a summary of the change and relevant context.

If your PR is related to a jira task, please add ticket ID in the pull request title so that it is linked.
For detailed instruction please check out [Workflow Automation Practice](https://cmusem.atlassian.net/wiki/spaces/SB/pages/1542127619/Workflow+Automation+practice).

# Test Plan

Please explain how this change will be tested.

- [ ] Unit test
- [ ] Integration test (including unit tests with supertest)
- [ ] Manual test (Please explain below for the test steps)
- [x] Not Applicable

# Task Link

Please add related jira task links

2023-03-23 22:37 UTC, jennyzeng requested changes
See inline comments

2023-03-23 22:37 UTC, jennyzeng commented on .circleci/config.yml
> +          command: npx jest --listTests | circleci tests run --command="xargs yarn test"  --batch-count=6  --fail-fast  --test-results-path="test-results"
do we really use yarn?

2023-03-25 07:16 UTC, Kaiwen-Bian approved these changes

2023-03-25 07:16 UTC, yueanz approved these changes

2023-03-25 21:26 UTC, jennyzeng approved these changes

2023-03-26 22:58 UTC, merged